CREATE TYPE wine_derivative_type AS enum (
'VINHO DE MESA',
'VINHO FINO DE MESA',
'VINHO FINO DE MESA (VINIFERA)',
'VINHO FRIZANTE',
'VINHO ORGÂNICO',
'VINHO ESPECIAL',
'ESPUMANTES',
'SUCO',
'SUCO DE UVAS',
'SUCO DE UVAS CONCENTRADO',
'DERIVADOS',
'OUTROS PRODUTOS COMERCIALIZADOS');
