CREATE TYPE wine_derivative_type AS enum (
'VINHO DE MESA',
'VINHO FINO DE MESA',
'VINHO FRIZANTE',
'VINHO ORGÂNICO',
'VINHO ESPECIAL',
'ESPUMANTES',
'SUCO DE UVAS',
'SUCO DE UVAS CONCENTRADO',
'OUTROS PRODUTOS COMERCIALIZADOS');
